### ISSUE TITLE
AttributeRelationshipType "None" cannot mean "data set level": description to be corrected

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#15]
AttributeRelationshipType "None" means that the value of the attribute **will not vary with any of the dimensions**. Since dimensions can be different from one dataset to another, and also because data sets are not identifiable (and thus cannot be stored in an SDMX database), those attributes cannot have values that depend on the dataset.  

If an attribute value must not vary with any of the dimensions, it must necessarily be the same for the whole data structure.

I propose to reword the current description   
"_This means that value of the attribute will not vary with any of the other key family components. This will always be treated as a data set level attribute._"  
to:   
"_This means that value of the attribute will not vary with any of the dimensions. The attribute will always be treated as a data structure level attribute. The level at which the unique attribute value will be presented in data messages depends on the data format._"

**Comment by sdmx3mdt** [comment]
Fixed in release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop

**Comment by dosse** [comment]
@sdmx3mdt Thanks, I see the changes in https://github.com/glennmdt/sdmx-ml/commit/9723414b246f2c4ef2f54d2c318480a036123d0c. Could you please check that this is also updated in the following places?:

- SDMX STANDARDS: SECTION 2: Chapter 5.3.2 Explanation of the Diagrams (in several places, "none" option is actually still missing.
- SDMX STANDARDS: SECTION 3A Part III (Structure): page 151 (see https://github.com/sdmx3mdt/sdmx-ml/blob/develop/documentation/SDMX_3-0_SECTION_3A_PART_III_STRUCTURE.doc)

**Comment by sdmx3mdt** [comment]
TWG/SWG Release Candidate Approval meeting 02 Sept 2021
Decision- replace the word 'None' with 'Dataflow' in the schemas and technical documentation for clarification purposes.

**Comment by dosse** [comment]
@sdmx3mdt I would propose to reword the current description "*This means that value of the attribute will not vary with any of the other key family components. This will always be treated as a data set level attribute.*" to:
"*This means that the value of the attribute varies per dataflow. It is the data modeller's responsibility to design or use non-overlapping dataflows that do not have observations in common, otherwise the integrity of dataflow-specific attribute values is not assured by the model, e.g. when querying those data through its DSD.*"

**Comment by sdmx3mdt** [comment]
Changed from None to Dataflow:
![image](https://user-images.githubusercontent.com/79863147/133433535-edae2c5c-a0bd-4762-b00a-a37626a157d7.png)
